/* Import CSS */
import 'bootstrap/dist/css/bootstrap.min.css'
import './App.css'
import './Header.css'
import './Footer.css'
import './BodyContainer.css'
import './FooterSpinner.css'
import './Setting.css'
import './Typewriter.css'
import './Home.css'
import './WebkitStyles.css'
import './LogSin.css'
import './DetailFlow.css'
import './Loader.scss'
